export const meta = {
  name: 'riji-mvp-build',
  description: '日迹小程序 MVP 角色分工：2架构师→3开发→3审查→1修复',
  phases: [
    { title: '架构', detail: '2 个架构师并行 → 契约校验 → 3 开发并行 → 3 审查并行 → 修复 → 测试' },
    { title: '开发', detail: '3 个开发 agent 并行，读取 CONTRACT.md 获取契约' },
    { title: '审查+测试', detail: 'UI+QA+自动化测试 3 agent 并行，报告写入文件' },
    { title: '修复', detail: '修复工程师从文件读取报告，逐条修复+重测+图标' },
    { title: '验收测试', detail: '测试工程师生成需求追溯矩阵+测试用例+验收清单 → test-plan.md' },
  ],
}

const PROJECT = '/media/mass/2T/download/daily-log/riji'

// ═══════════════════════════════════════════════════════════════
// Phase 1: 架构师（2 agent 并行）
// ═══════════════════════════════════════════════════════════════
phase('架构')

const architectResults = await parallel([
  // ── 架构师 A: 项目配置 + 全局样式 ──
  () => agent(
    [
      '# 角色：微信小程序架构师（配置+样式）',
      '',
      '## 你的职责',
      '负责项目骨架：app.json / app.wxss / app.js / 目录创建 / CONTRACT.md。',
      '你的产出是所有下游 agent 的共同契约。',
      '',
      `## 项目路径：${PROJECT}`,
      '',
      '---',
      '',
      '## 任务 1：修正 app.json',
      '',
      '先读取现有文件，保留 appid 等已有配置，修改为 4 个 tab + 7 个页面：',
      '',
      '```json',
      '{',
      '  "pages": [',
      '    "pages/index/index",',
      '    "pages/todos/todos",',
      '    "pages/memos/memos",',
      '    "pages/mine/mine",',
      '    "pages/calendar/calendar",',
      '    "pages/detail/detail",',
      '    "pages/write/write"',
      '  ],',
      '  "tabBar": {',
      '    "color": "#999999",',
      '    "selectedColor": "#2c3e3e",',
      '    "backgroundColor": "#ffffff",',
      '    "borderStyle": "black",',
      '    "list": [',
      '      { "pagePath": "pages/index/index", "text": "今天", "iconPath": "assets/today.png", "selectedIconPath": "assets/today-active.png" },',
      '      { "pagePath": "pages/todos/todos", "text": "待办", "iconPath": "assets/todo.png", "selectedIconPath": "assets/todo-active.png" },',
      '      { "pagePath": "pages/memos/memos", "text": "备忘", "iconPath": "assets/memo.png", "selectedIconPath": "assets/memo-active.png" },',
      '      { "pagePath": "pages/mine/mine", "text": "我的", "iconPath": "assets/mine.png", "selectedIconPath": "assets/mine-active.png" }',
      '    ]',
      '  }',
      '}',
      '```',
      '',
      '---',
      '',
      '## 任务 2：更新 app.js',
      '',
      '在现有基础上扩展 onLaunch，加上全局数据：',
      '',
      '```javascript',
      'const storage = require("./utils/storage");',
      'App({',
      '  onLaunch() {',
      '    const { usedKB, limitKB } = storage.getStorageUsage();',
      '    console.log("日迹启动 - 存储:", usedKB, "KB /", limitKB, "KB");',
      '    if (usedKB > limitKB * 0.8) {',
      '      console.warn("存储空间不足");',
      '    }',
      '  },',
      '  globalData: {',
      '    version: "1.0.0",',
      '  },',
      '});',
      '```',
      '',
      '---',
      '',
      '## 任务 3：全局样式 app.wxss',
      '',
      '完整的设计令牌体系。主色调 #2c3e3e，简洁素白。',
      '',
      '```css',
      'page {',
      '  --color-primary: #2c3e3e;',
      '  --color-primary-light: #3d5454;',
      '  --color-bg: #f5f5f5;',
      '  --color-card: #ffffff;',
      '  --color-text: #333333;',
      '  --color-text-secondary: #666666;',
      '  --color-text-muted: #999999;',
      '  --color-border: #e8e8e8;',
      '  --color-success: #52c41a;',
      '  --color-danger: #e74c3c;',
      '  --color-warning: #faad14;',
      '  --color-highlight: #e8f4f0;',
      '  --radius-sm: 6px;',
      '  --radius-md: 8px;',
      '  --radius-lg: 12px;',
      '  --shadow-sm: 0 1px 3px rgba(0,0,0,0.06);',
      '  --shadow-md: 0 2px 8px rgba(0,0,0,0.1);',
      '  --font-xs: 12px; --font-sm: 14px; --font-md: 16px; --font-lg: 18px; --font-xl: 22px;',
      '  --spacing-xs: 4px; --spacing-sm: 8px; --spacing-md: 12px; --spacing-lg: 16px; --spacing-xl: 24px;',
      '  --transition-fast: 0.15s ease; --transition-normal: 0.25s ease;',
      '}',
      '',
      'page { font-family: -apple-system, BlinkMacSystemFont, sans-serif; font-size: var(--font-md); color: var(--color-text); background: var(--color-bg); line-height: 1.6; }',
      '',
      '/* 卡片 */',
      '.card { background: var(--color-card); border-radius: var(--radius-md); padding: var(--spacing-lg); margin: var(--spacing-md) var(--spacing-lg); box-shadow: var(--shadow-sm); }',
      '',
      '/* 日期头部 */',
      '.date-header { display: flex; align-items: center; justify-content: center; padding: var(--spacing-lg); gap: var(--spacing-lg); }',
      '.date-header .arrow { font-size: var(--font-xl); color: var(--color-primary); padding: var(--spacing-xs) var(--spacing-sm); }',
      '.date-header .date-text { font-size: var(--font-lg); font-weight: 600; color: var(--color-primary); }',
      '.date-header .weekday { font-size: var(--font-sm); color: var(--color-text-muted); }',
      '',
      '/* 连续天数 */',
      '.streak-badge { display: flex; align-items: center; justify-content: center; gap: var(--spacing-xs); padding: var(--spacing-sm) 0; font-size: var(--font-sm); color: var(--color-warning); }',
      '',
      '/* 区块标题 */',
      '.section-title { font-size: var(--font-sm); color: var(--color-text-muted); padding: var(--spacing-sm) var(--spacing-lg); text-transform: uppercase; letter-spacing: 1px; }',
      '',
      '/* 按钮 */',
      '.btn-primary { background: var(--color-primary); color: #fff; border-radius: var(--radius-md); padding: var(--spacing-md) var(--spacing-xl); font-size: var(--font-md); text-align: center; border: none; }',
      '.btn-outline { background: transparent; color: var(--color-primary); border: 1px solid var(--color-primary); border-radius: var(--radius-md); padding: var(--spacing-md) var(--spacing-xl); font-size: var(--font-md); text-align: center; }',
      '.btn-danger { background: var(--color-danger); color: #fff; border-radius: var(--radius-md); padding: var(--spacing-md) var(--spacing-xl); font-size: var(--font-md); text-align: center; border: none; }',
      '.btn-sm { padding: var(--spacing-xs) var(--spacing-md); font-size: var(--font-sm); }',
      '',
      '/* 操作栏 */',
      '.action-bar { display: flex; gap: var(--spacing-sm); padding: var(--spacing-md) var(--spacing-lg); flex-wrap: wrap; }',
      '',
      '/* 空状态 */',
      '.empty-state { display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 60px 20px; color: var(--color-text-muted); }',
      '.empty-state .icon { font-size: 48px; margin-bottom: var(--spacing-md); }',
      '.empty-state .text { font-size: var(--font-md); }',
      '',
      '/* 已完成 */',
      '.done { text-decoration: line-through; color: var(--color-text-muted); }',
      '',
      '/* 间距 */',
      '.mt-8 { margin-top: 8px; } .mt-12 { margin-top: 12px; } .mt-16 { margin-top: 16px; } .mt-24 { margin-top: 24px; }',
      '.mb-8 { margin-bottom: 8px; } .mb-16 { margin-bottom: 16px; }',
      '.p-12 { padding: 12px; } .p-16 { padding: 16px; }',
      '',
      '/* 动画 */',
      '.scale-in { animation: scaleIn var(--transition-fast) ease-out; }',
      '@keyframes scaleIn { from { transform: scale(0.8); opacity: 0.5; } to { transform: scale(1); opacity: 1; } }',
      '.fill-green { transition: background-color var(--transition-normal); }',
      '.fill-green.active { background-color: var(--color-success); color: #fff; }',
      '',
      '/* 进度条 */',
      '.progress-bar { height: 6px; background: var(--color-border); border-radius: 3px; overflow: hidden; }',
      '.progress-bar .fill { height: 100%; background: var(--color-primary); border-radius: 3px; transition: width var(--transition-normal); }',
      '```',
      '',
      '---',
      '',
      '## 任务 4：创建所有目录',
      '',
      '```bash',
      `mkdir -p ${PROJECT}/pages/todos ${PROJECT}/pages/memos ${PROJECT}/pages/mine`,
      `mkdir -p ${PROJECT}/pages/calendar ${PROJECT}/pages/write ${PROJECT}/pages/detail`,
      `mkdir -p ${PROJECT}/components/mood-picker ${PROJECT}/components/habit-check`,
      `mkdir -p ${PROJECT}/components/todo-item ${PROJECT}/components/memo-item`,
      `mkdir -p ${PROJECT}/components/empty-state ${PROJECT}/components/calendar`,
      `mkdir -p ${PROJECT}/components/entry-card ${PROJECT}/components/tag-input`,
      `mkdir -p ${PROJECT}/assets`,
      '```',
      '',
      '---',
      '',
      '## 任务 5：安装 TDesign 依赖',
      '',
      '```bash',
      `cd ${PROJECT} && npm init -y 2>/dev/null || true`,
      `cd ${PROJECT} && npm install tdesign-miniprogram`,
      '```',
      '',
      '如果 npm 不可用，跳过此步并在输出中注明。',
      '',
      '---',
      '',
      '## 任务 6：写入 CONTRACT.md',
      '',
      `写入文件 ${PROJECT}/CONTRACT.md，内容为以下纯文本（下游所有 agent 启动时先读此文件）：`,
      '',
      '```markdown',
      '# 日迹 设计契约',
      '',
      '## 路由表',
      '| 页面 | 路径 | 跳转方式 |',
      '|------|------|----------|',
      '| 首页(Tab) | /pages/index/index | switchTab |',
      '| 待办(Tab) | /pages/todos/todos | switchTab |',
      '| 备忘(Tab) | /pages/memos/memos | switchTab |',
      '| 我的(Tab) | /pages/mine/mine | switchTab |',
      '| 月历 | /pages/calendar/calendar | navigateTo |',
      '| 详情 | /pages/detail/detail?date=YYYY-MM-DD | navigateTo |',
      '| 写总结 | /pages/write/write?date=YYYY-MM-DD | navigateTo |',
      '',
      '## CSS 全局 class（禁止 WXML inline style）',
      '卡片: .card',
      '日期: .date-header .arrow .date-text .weekday',
      '连续: .streak-badge',
      '标题: .section-title',
      '按钮: .btn-primary .btn-outline .btn-danger .btn-sm',
      '操作: .action-bar',
      '空态: .empty-state .icon .text',
      '完成: .done',
      '间距: .mt-8 .mt-12 .mt-16 .mt-24 .mb-8 .mb-16 .p-12 .p-16',
      '动画: .scale-in .fill-green .fill-green.active',
      '进度: .progress-bar .fill',
      'CSS 变量: --color-primary --color-bg --color-card --color-text --color-text-muted',
      '  --color-danger --color-success --color-warning --color-highlight',
      '  --radius-md --shadow-sm --spacing-lg --transition-fast --transition-normal',
      '',
      '## storage API（唯一允许直接调 wx.Storage 的模块）',
      '```',
      'const storage = require("../../utils/storage")',
      '// 日总结',
      'storage.getEntry(date) → {content, tags, created_at, updated_at} | null',
      'storage.saveEntry(date, {content, tags})',
      'storage.deleteEntry(date)',
      'storage.getAllEntries() → [{date, content, tags, created_at, updated_at}]  // 统计/月历用',
      '// 心情',
      'storage.getMood(date) → emoji | null',
      'storage.saveMood(date, emoji|null)',
      'storage.getAllMoods() → {date: emoji, ...}  // 月历用',
      '// 习惯定义',
      'storage.getHabitDefs() → [{id, name, icon, order, created_at}]',
      'storage.saveHabitDef({id?, name, icon, order?}) → id',
      'storage.deleteHabitDef(id)',
      '// 习惯打卡',
      'storage.getHabits(date) → {habit_id: bool}',
      'storage.toggleHabit(date, habitId)',
      '// 待办',
      'storage.getTodos() → [{id, title, deadline, note, done, created_at}]',
      'storage.saveTodo({id?, title, deadline?, note?, done?}) → id',
      'storage.deleteTodo(id)',
      '// 备忘',
      'storage.getMemos() → [{id, title, content, created_at, updated_at}]  (按创建时间倒序)',
      'storage.saveMemo({id?, title, content}) → id',
      'storage.deleteMemo(id)',
      '// 存储',
      'storage.getStorageUsage() → {usedKB, limitKB}',
      'storage.getSetting(key) / saveSetting(key, value)',
      'storage.clearAll()  // 清空所有数据（危险操作，调用前必须二次确认）',
      'storage.genId() → 唯一 ID',
      '```',
      '',
      '## date 工具',
      '```',
      'const dateUtil = require("../../utils/date")',
      'dateUtil.getToday() → "YYYY-MM-DD"',
      'dateUtil.formatDate(date) / parseDate(str)',
      'dateUtil.getWeekday(date) → "星期X"',
      'dateUtil.getMonthStr(date) → "2026年6月"',
      'dateUtil.addDays(dateStr, n) / addMonths(dateStr, n)',
      'dateUtil.getMonthCalendar(yearMonth) → [[day,...], ...]',
      '```',
      '',
      '## streak 工具',
      '```',
      'const streak = require("../../utils/streak")',
      'streak.getStreak() → 连续天数',
      '```',
      '',
      '## export 工具',
      '```',
      'const exp = require("../../utils/export")',
      'exp.exportAll() → JSON 字符串（调用后需 wx.getFileSystemManager().writeFile 写临时文件，再 wx.shareFileMessage 分享）',
      'exp.importData(jsonStr) → {success, added?, updated?, error?}',
      'exp.archiveYear(year) → JSON 字符串',
      'exp.deleteYearData(year)',
      '```',
      '',
      '## TDesign 组件速查',
      't-textarea: <t-textarea value="{{x}}" placeholder="..." bind:change="onX" autosize />',
      't-tag: <t-tag theme="primary" size="small">{{label}}</t-tag>',
      't-tag closable: <t-tag closable bind:close="onRemove">{{label}}</t-tag>',
      't-dialog: <t-dialog visible="{{show}}" title="..." content="..." bind:confirm="onOK" bind:cancel="onCancel" />',
      't-toast: wx.showToast({ title: "...", icon: "success" })',
      't-picker: <t-picker visible="{{show}}" value="{{val}}" bind:change="onPick" bind:cancel="onCancel" />',
      't-popup: <t-popup visible="{{show}}" placement="bottom" bind:visible-change="onClose">...</t-popup>',
      't-tabs: <t-tabs value="{{tab}}" bind:change="onTab"><t-tab-panel label="全部" value="all" />...</t-tabs>',
      't-icon: <t-icon name="add" size="24px" />',
      't-input: <t-input value="{{x}}" placeholder="..." bind:change="onX" />',
      't-button: <t-button theme="primary" size="medium" bind:tap="onX">按钮</t-button>',
      '',
      '## 铁律',
      '1. 禁止 WXML 中写 style="..." 内联样式',
      '2. 禁止直接调 wx.setStorageSync / wx.getStorageSync / wx.removeStorageSync（例外：utils/streak.js 读 entry_ 判断连续天数；utils/export.js 导入导出需遍历全部 key）',
      '3. 跳转 Tab 页面必须用 wx.switchTab，子页面用 wx.navigateTo',
      '4. 所有数据读写走 storage 模块，所有日期处理走 dateUtil',
      '```',
    ].join('\n'),
    { label: '架构师A:配置+样式', phase: '架构' }
  ),

  // ── 架构师 B: 工具函数 ──
  () => agent(
    [
      '# 角色：微信小程序架构师（工具函数）',
      '',
      '## 你的职责',
      '实现 4 个工具模块。所有页面和组件都依赖这些模块，必须稳健、API 签名不随意变。',
      '',
      `## 项目路径：${PROJECT}`,
      '',
      '---',
      '',
      '## 任务 1：utils/storage.js',
      '',
      '这是整个项目唯一允许直接调用 wx.setStorageSync 的文件。',
      '',
      '```javascript',
      '// utils/storage.js',
      '// 存储 key 约定：',
      '//   entry_YYYY-MM-DD  → 日总结    {content, tags, created_at, updated_at}',
      '//   mood_YYYY-MM-DD   → 心情      {emoji}',
      '//   habit_YYYY-MM-DD  → 习惯打卡  {habit_id: true/false}',
      '//   todo_<id>         → 待办      {id, title, deadline, note, done, created_at}',
      '//   memo_<id>         → 备忘      {id, title, content, created_at, updated_at}',
      '//   habit_def_<id>    → 习惯定义  {id, name, icon, order, created_at}',
      '//   settings_<key>    → 设置项',
      '',
      'function genId() {',
      '  return Date.now().toString(36) + Math.random().toString(36).slice(2, 6);',
      '}',
      '',
      '// ── 日总结 ──',
      'function getEntry(date) { return wx.getStorageSync("entry_" + date) || null; }',
      'function saveEntry(date, data) {',
      '  const existing = getEntry(date);',
      '  const now = Date.now();',
      '  wx.setStorageSync("entry_" + date, {',
      '    content: data.content || "",',
      '    tags: data.tags || [],',
      '    created_at: existing ? existing.created_at : now,',
      '    updated_at: now',
      '  });',
      '  checkStorageLimit();',
      '}',
      'function deleteEntry(date) { wx.removeStorageSync("entry_" + date); }',
      'function getAllEntries() {',
      '  return wx.getStorageInfoSync().keys',
      '    .filter(k => k.startsWith("entry_"))',
      '    .map(k => ({ date: k.replace("entry_", ""), ...wx.getStorageSync(k) }));',
      '}',
      '',
      '// ── 心情 ──',
      'function getMood(date) {',
      '  const d = wx.getStorageSync("mood_" + date);',
      '  return d ? d.emoji : null;',
      '}',
      'function saveMood(date, emoji) {',
      '  if (emoji) { wx.setStorageSync("mood_" + date, { emoji }); }',
      '  else { wx.removeStorageSync("mood_" + date); }',
      '  checkStorageLimit();',
      '}',
      'function getAllMoods() {',
      '  const result = {};',
      '  wx.getStorageInfoSync().keys',
      '    .filter(k => k.startsWith("mood_"))',
      '    .forEach(k => { result[k.replace("mood_", "")] = wx.getStorageSync(k).emoji; });',
      '  return result;',
      '}',
      '',
      '// ── 习惯定义 ──',
      'function getHabitDefs() {',
      '  return wx.getStorageInfoSync().keys',
      '    .filter(k => k.startsWith("habit_def_"))',
      '    .map(k => wx.getStorageSync(k))',
      '    .sort((a, b) => a.order - b.order);',
      '}',
      'function saveHabitDef(def) {',
      '  const id = def.id || genId();',
      '  const existing = wx.getStorageSync("habit_def_" + id);',
      '  wx.setStorageSync("habit_def_" + id, {',
      '    id,',
      '    name: def.name,',
      '    icon: def.icon || "📌",',
      '    order: def.order !== undefined ? def.order : getHabitDefs().length,',
      '    created_at: existing ? existing.created_at : Date.now()',
      '  });',
      '  return id;',
      '}',
      'function deleteHabitDef(id) { wx.removeStorageSync("habit_def_" + id); }',
      '',
      '// ── 习惯打卡 ──',
      'function getHabits(date) { return wx.getStorageSync("habit_" + date) || {}; }',
      'function toggleHabit(date, habitId) {',
      '  const habits = getHabits(date);',
      '  habits[habitId] = !habits[habitId];',
      '  wx.setStorageSync("habit_" + date, habits);',
      '  checkStorageLimit();',
      '}',
      '',
      '// ── 待办 ──',
      'function getTodos() {',
      '  return wx.getStorageInfoSync().keys',
      '    .filter(k => k.startsWith("todo_"))',
      '    .map(k => wx.getStorageSync(k));',
      '}',
      'function saveTodo(todo) {',
      '  const id = todo.id || genId();',
      '  const existing = wx.getStorageSync("todo_" + id);',
      '  wx.setStorageSync("todo_" + id, {',
      '    id,',
      '    title: todo.title,',
      '    deadline: todo.deadline || null,',
      '    note: todo.note || "",',
      '    done: todo.done || false,',
      '    created_at: existing ? existing.created_at : Date.now()',
      '  });',
      '  checkStorageLimit();',
      '  return id;',
      '}',
      'function deleteTodo(id) { wx.removeStorageSync("todo_" + id); }',
      '',
      '// ── 备忘 ──',
      'function getMemos() {',
      '  return wx.getStorageInfoSync().keys',
      '    .filter(k => k.startsWith("memo_"))',
      '    .map(k => wx.getStorageSync(k))',
      '    .sort((a, b) => b.created_at - a.created_at);',
      '}',
      'function saveMemo(memo) {',
      '  const id = memo.id || genId();',
      '  const existing = wx.getStorageSync("memo_" + id);',
      '  wx.setStorageSync("memo_" + id, {',
      '    id,',
      '    title: memo.title,',
      '    content: memo.content || "",',
      '    created_at: existing ? existing.created_at : Date.now(),',
      '    updated_at: Date.now()',
      '  });',
      '  checkStorageLimit();',
      '  return id;',
      '}',
      'function deleteMemo(id) { wx.removeStorageSync("memo_" + id); }',
      '',
      '// ── 存储用量 ──',
      'function getStorageUsage() {',
      '  const info = wx.getStorageInfoSync();',
      '  return { usedKB: info.currentSize, limitKB: info.limitSize || 10240 };',
      '}',
      'function checkStorageLimit() {',
      '  const { usedKB, limitKB } = getStorageUsage();',
      '  if (usedKB > limitKB * 0.8) {',
      '    wx.showToast({ title: "存储空间不足，请导出备份后清理", icon: "none", duration: 3000 });',
      '  }',
      '}',
      '',
      '// ── 设置 ──',
      'function getSetting(key) { return wx.getStorageSync("settings_" + key); }',
      'function saveSetting(key, value) { wx.setStorageSync("settings_" + key, value); }',
      '',
      '// ── 清空 ──',
      'function clearAll() {',
      '  const keys = wx.getStorageInfoSync().keys;',
      '  keys.forEach(k => wx.removeStorageSync(k));',
      '}',
      '',
      'module.exports = {',
      '  genId,',
      '  getEntry, saveEntry, deleteEntry, getAllEntries,',
      '  getMood, saveMood, getAllMoods,',
      '  getHabitDefs, saveHabitDef, deleteHabitDef,',
      '  getHabits, toggleHabit,',
      '  getTodos, saveTodo, deleteTodo,',
      '  getMemos, saveMemo, deleteMemo,',
      '  getStorageUsage,',
      '  getSetting, saveSetting,',
      '  clearAll,',
      '};',
      '```',
      '',
      '---',
      '',
      '## 任务 2：utils/date.js',
      '',
      '```javascript',
      '// utils/date.js',
      'function formatDate(date) {',
      '  const y = date.getFullYear();',
      '  const m = String(date.getMonth() + 1).padStart(2, "0");',
      '  const d = String(date.getDate()).padStart(2, "0");',
      '  return y + "-" + m + "-" + d;',
      '}',
      'function parseDate(str) {',
      '  const [y, m, d] = str.split("-").map(Number);',
      '  return new Date(y, m - 1, d);',
      '}',
      'function getToday() { return formatDate(new Date()); }',
      'function getWeekday(date) {',
      '  return "星期" + ["日", "一", "二", "三", "四", "五", "六"][date.getDay()];',
      '}',
      'function getMonthStr(date) {',
      '  return date.getFullYear() + "年" + (date.getMonth() + 1) + "月";',
      '}',
      'function addDays(dateStr, n) {',
      '  const d = parseDate(dateStr);',
      '  d.setDate(d.getDate() + n);',
      '  return formatDate(d);',
      '}',
      'function addMonths(dateStr, n) {',
      '  const d = parseDate(dateStr + "-01");',
      '  d.setMonth(d.getMonth() + n);',
      '  return formatDate(d).slice(0, 7);',
      '}',
      'function getDaysInMonth(ym) {',
      '  const [y, m] = ym.split("-").map(Number);',
      '  return new Date(y, m, 0).getDate();',
      '}',
      'function getFirstDayOfWeek(ym) {',
      '  const [y, m] = ym.split("-").map(Number);',
      '  return new Date(y, m - 1, 1).getDay();',
      '}',
      '// 周一为一周第一天，周日(getDay()=0)放末尾，前面补6个空位',
      'function getMonthCalendar(ym) {',
      '  const days = getDaysInMonth(ym);',
      '  const firstDay = getFirstDayOfWeek(ym);',
      '  const weeks = [];',
      '  let week = new Array(firstDay === 0 ? 6 : firstDay - 1).fill(null);  // 周日→6空位，周一→0空位',
      '  for (let d = 1; d <= days; d++) {',
      '    week.push(d);',
      '    if (week.length === 7) { weeks.push(week); week = []; }',
      '  }',
      '  if (week.length > 0) {',
      '    while (week.length < 7) week.push(null);',
      '    weeks.push(week);',
      '  }',
      '  return weeks;',
      '}',
      'module.exports = {',
      '  formatDate, parseDate, getToday, getWeekday, getMonthStr,',
      '  addDays, addMonths, getDaysInMonth, getFirstDayOfWeek, getMonthCalendar,',
      '};',
      '```',
      '',
      '---',
      '',
      '## 任务 3：utils/streak.js',
      '',
      '```javascript',
      '// utils/streak.js',
      '// 仅统计 entry_ 的连续天数。每次调用遍历 entry_ key，数据量小时开销可忽略（< 50ms）。',
      '// 优化提示：可加一个 {streak, cachedDate} 内存缓存，仅当日期变化时重算，避免 onShow 重复遍历。',
      'const { getToday, addDays } = require("./date");',
      '',
      'function getStreak() {',
      '  let streak = 0;',
      '  let date = getToday();',
      '  while (wx.getStorageSync("entry_" + date)) {',
      '    streak++;',
      '    date = addDays(date, -1);',
      '  }',
      '  if (streak === 0) {',
      '    date = addDays(getToday(), -1);',
      '    while (wx.getStorageSync("entry_" + date)) {',
      '      streak++;',
      '      date = addDays(date, -1);',
      '    }',
      '  }',
      '  return streak;',
      '}',
      'module.exports = { getStreak };',
      '```',
      '',
      '---',
      '',
      '## 任务 4：utils/export.js',
      '',
      '```javascript',
      '// utils/export.js',
      'function exportAll() {',
      '  const keys = wx.getStorageInfoSync().keys;',
      '  const data = {',
      '    version: 2,',
      '    app_name: "日迹",',
      '    exported_at: new Date().toISOString(),',
      '    entries: [],',
      '    todos: [],',
      '    memos: [],',
      '    moods: {},',
      '    habit_defs: [],',
      '    habits: {},',
      '  };',
      '  keys.forEach(k => {',
      '    const v = wx.getStorageSync(k);',
      '    if (k.startsWith("entry_")) {',
      '      data.entries.push({ date: k.replace("entry_", ""), ...v });',
      '    } else if (k.startsWith("todo_")) {',
      '      data.todos.push(v);',
      '    } else if (k.startsWith("memo_")) {',
      '      data.memos.push(v);',
      '    } else if (k.startsWith("mood_")) {',
      '      data.moods[k.replace("mood_", "")] = v.emoji;',
      '    } else if (k.startsWith("habit_def_")) {',
      '      data.habit_defs.push(v);',
      '    } else if (k.startsWith("habit_") && !k.startsWith("habit_def_")) {',
      '      data.habits[k.replace("habit_", "")] = v;',
      '    }',
      '  });',
      '  return JSON.stringify(data, null, 2);',
      '}',
      '',
      'function importData(jsonStr) {',
      '  let data;',
      '  try { data = JSON.parse(jsonStr); } catch (e) {',
      '    return { success: false, error: "JSON 格式无效" };',
      '  }',
      '  // 导入前检查体积（currentSize 单位 KB，jsonStr.length 是字符数，近似 2 字节/字符）',
      '  const currentSizeKB = wx.getStorageInfoSync().currentSize;',
      '  const incomingSizeKB = (jsonStr.length * 2) / 1024;',
      '  if (currentSizeKB + incomingSizeKB > 9 * 1024) {  // 9MB = 9216KB',
      '    return { success: false, error: "数据过大，请先清理历史数据" };',
      '  }',
      '  let added = 0, updated = 0;',
      '  (data.habit_defs || []).forEach(d => {',
      '    const k = "habit_def_" + d.id;',
      '    const e = wx.getStorageSync(k);',
      '    wx.setStorageSync(k, d);',
      '    e ? updated++ : added++;',
      '  });',
      '  (data.entries || []).forEach(e => {',
      '    const k = "entry_" + e.date;',
      '    const x = wx.getStorageSync(k);',
      '    wx.setStorageSync(k, {',
      '      content: e.content, tags: e.tags || [],',
      '      created_at: e.created_at, updated_at: e.updated_at || e.created_at',
      '    });',
      '    x ? updated++ : added++;',
      '  });',
      '  Object.entries(data.moods || {}).forEach(([d, emoji]) => {',
      '    const k = "mood_" + d;',
      '    const x = wx.getStorageSync(k);',
      '    wx.setStorageSync(k, { emoji });',
      '    x ? updated++ : added++;',
      '  });',
      '  Object.entries(data.habits || {}).forEach(([d, habits]) => {',
      '    const k = "habit_" + d;',
      '    const x = wx.getStorageSync(k) || {};',
      '    wx.setStorageSync(k, { ...x, ...habits });',
      '    Object.keys(habits).length > 0 ? updated++ : added++;',
      '  });',
      '  (data.todos || []).forEach(t => {',
      '    const k = "todo_" + t.id;',
      '    const x = wx.getStorageSync(k);',
      '    wx.setStorageSync(k, t);',
      '    x ? updated++ : added++;',
      '  });',
      '  (data.memos || []).forEach(m => {',
      '    const k = "memo_" + m.id;',
      '    const x = wx.getStorageSync(k);',
      '    wx.setStorageSync(k, m);',
      '    x ? updated++ : added++;',
      '  });',
      '  return { success: true, added, updated };',
      '}',
      '',
      'function archiveYear(year) {',
      '  const keys = wx.getStorageInfoSync().keys;',
      '  const archive = {};',
      '  const datePrefixes = ["entry_", "mood_", "habit_"];  // 只归档日期型数据，避免误匹配 todo_/memo_/habit_def_ ID',
      '  keys.forEach(k => {',
      '    if (datePrefixes.some(p => k.startsWith(p)) && k.includes(year + "-")) {',
      '      archive[k] = wx.getStorageSync(k);',
      '    }',
      '  });',
      '  return JSON.stringify(archive);',
      '}',
      '',
      'function deleteYearData(year) {',
      '  const keys = wx.getStorageInfoSync().keys;',
      '  const datePrefixes = ["entry_", "mood_", "habit_"];  // 只删除日期型数据',
      '  keys.forEach(k => {',
      '    if (datePrefixes.some(p => k.startsWith(p)) && k.includes(year + "-")) {',
      '      wx.removeStorageSync(k);',
      '    }',
      '  });',
      '}',
      '',
      'module.exports = { exportAll, importData, archiveYear, deleteYearData };',
      '```',
    ].join('\n'),
    { label: '架构师B:工具函数', phase: '架构' }
  ),
])

log(`架构完成：${architectResults.filter(Boolean).length}/2 个架构师成功`)

// ═══════════════════════════════════════════════════════════════
// 契约校验：比对 CONTRACT.md 与 utils/*.js 的 module.exports
// ═══════════════════════════════════════════════════════════════
log('校验契约与实际实现的一致性...')

const contractCheck = await agent(
  [
    '# 角色：契约校验',
    '',
    '## 任务：比对 CONTRACT.md 与 utils/*.js 的 API 签名是否一致',
    '',
    `1. 读取 ${PROJECT}/CONTRACT.md，提取 storage API / date 工具 / streak 工具 / export 工具的导出函数名`,
    `2. 读取 ${PROJECT}/utils/storage.js、date.js、streak.js、export.js 的 module.exports`,
    `3. 逐项比对：`,
    '   - CONTRACT.md 声明的函数是否都在 module.exports 中？',
    '   - module.exports 中是否有 CONTRACT.md 未声明的函数？',
    `4. 不一致则直接修正 CONTRACT.md（用 Edit 工具更新），确保下游 agent 看到的是准确契约`,
    '',
    '输出：比对结果（一致/修正了 X 处）',
  ].join('\n'),
  { label: '契约校验', phase: '架构' }
)

log(`契约校验：${contractCheck ? '完成' : '跳过'}`)

// ═══════════════════════════════════════════════════════════════
// Phase 2: 开发团队（3 agent 并行）
// 每个 agent 启动时先读取 CONTRACT.md
// ═══════════════════════════════════════════════════════════════
phase('开发')

const CONTRACT_HEADER = `先读取 ${PROJECT}/CONTRACT.md 获取完整契约，然后严格按契约开发。`

const devResults = await parallel([
  // ── Dev A: 首页 ──
  () => agent(
    [
      CONTRACT_HEADER,
      '',
      '# 角色：前端开发工程师（首页模块）',
      '',
      `先读取 ${PROJECT}/pages/index/index.js 了解现有代码（如果文件不存在或为空，则从零创建 Page({})）。有代码就在上面扩展，不要从零重写。`,
      '',
      '## 你的文件',
      `- ${PROJECT}/pages/index/index.{js,wxml,wxss,json}`,
      `- ${PROJECT}/components/mood-picker/mood-picker.{js,wxml,wxss,json}`,
      `- ${PROJECT}/components/habit-check/habit-check.{js,wxml,wxss,json}`,
      `- ${PROJECT}/components/entry-card/entry-card.{js,wxml,wxss,json}`,
      '',
      '## 首页功能',
      '',
      '### 日期头部',
      '- ← → 箭头切日期（dateUtil.addDays），点击日期文字弹出 t-picker',
      '- 显示星期 + 连续天数（streak.getStreak()）',
      '',
      '### 心情选择器（mood-picker 组件）',
      '- 5 个表情：😊 😄 😐 😞 😡，水平排列',
      '- 点击未选中→选中并替换，调 storage.saveMood(date, emoji)',
      '- 点击已选中→取消选中，调 storage.saveMood(date, null)',
      '- 选中时 CSS transform: scale(1.2) + .scale-in 动画',
      '- 组件属性：date',
      '',
      '### 习惯打卡（habit-check 组件）',
      '- storage.getHabitDefs() 获取定义列表',
      '- storage.getHabits(date) 获取当天状态',
      '- 渲染 ☑️/☐，点击 toggle 调 storage.toggleHabit(date, id)',
      '- 打勾时 .fill-green.active 绿色填充',
      '- 找不到 def 的 habit_id 跳过不显示（orphan 数据）',
      '- 组件属性：date',
      '',
      '### 日总结（entry-card 组件）',
      '- 未写：t-textarea + 随机 placeholder（5 条引导语：',
      '  "今天最有成就感的一件事是什么？"',
      '  "今天遇到了什么有趣的人或事？"',
      '  "今天学到了什么新东西？"',
      '  "今天的心情怎么样？发生了什么？"',
      '  "今天完成了哪些重要的事？"）',
      '- 已写：内容 + t-tag 标签 + 字数 + "续写""删除"按钮',
      '- 续写→navigateTo /pages/write/write?date=xxx',
      '- 删除→t-dialog 确认后 storage.deleteEntry(date)',
      '- 保存→storage.saveEntry(date, {content, tags})，Toast "已保存"',
      '',
      '### 今日待办预览',
      '- 筛选 deadline ≤ 今天 且 !done 的待办',
      '- 无 deadline 的不显示（需求明确规定）',
      '- 按 deadline 升序，最多 5 条',
      '- 点击方框完成→storage.saveTodo({...todo, done: true})',
      '- >5 条显示"查看全部→"，switchTab 到待办页',
      '- 0 条显示"今天没有待办，轻松的一天 ~"',
      '',
      '## 铁律',
      '- 禁止 WXML 中写 style="..."',
      '- 禁止直接调 wx.Storage 系列 API',
      '- index.json 的 usingComponents 注册所有组件',
    ].join('\n'),
    { label: 'DevA:首页', phase: '开发' }
  ),

  // ── Dev B: 待办 + 备忘 ──
  () => agent(
    [
      CONTRACT_HEADER,
      '',
      '# 角色：前端开发工程师（待办+备忘模块）',
      '',
      `先读取 ${PROJECT}/pages/todos/todos.js 和 ${PROJECT}/pages/memos/memos.js（如果文件不存在或为空，则从零创建 Page({})）。`,
      '',
      '## 你的文件',
      `待办: ${PROJECT}/pages/todos/todos.{js,wxml,wxss,json}`,
      `      ${PROJECT}/components/todo-item/todo-item.{js,wxml,wxss,json}`,
      `备忘: ${PROJECT}/pages/memos/memos.{js,wxml,wxss,json}`,
      `      ${PROJECT}/components/memo-item/memo-item.{js,wxml,wxss,json}`,
      '',
      '## 待办页',
      '',
      '### 添加弹窗',
      '- t-popup 底部弹出，标题(t-input 必填)+截止日期(t-picker 可选)+备注(t-textarea 可选)+保存',
      '- 保存→storage.saveTodo()→关闭弹窗→刷新',
      '',
      '### 筛选 Tab',
      '- t-tabs: 全部/待完成(done===false)/已完成(done===true)',
      '',
      '### 列表',
      '- 按日期分组（今天→明天→未来），每组标题显示日期',
      '- 组内排序：有 deadline 按升序→无 deadline→已完成',
      '- todo-item 组件渲染，属性：todo 对象',
      '- 点击方框 toggle done，已完成 .done class（灰色+划线）',
      '- 点击条目→编辑弹窗（预填数据）',
      '- 长按→t-dialog 删除确认',
      '- 空状态："还没有待办，轻松的一天 ~"',
      '',
      '### todo-item 组件',
      '- 显示：勾选框+标题+截止时间(如有)+备注(如有)',
      '- 事件（triggerEvent 名，父组件用 bind:toggle / bind:tap / bind:longpress 监听）：toggle, tap, longpress',
      '',
      '## 备忘页',
      '',
      '### 添加/编辑弹窗',
      '- t-popup 底部弹出，标题(t-input)+内容(t-textarea 不限字数)+保存',
      '- 保存→storage.saveMemo()→关闭弹窗→刷新',
      '- 内容>5000字 Toast "内容较长，建议拆分"',
      '',
      '### 列表',
      '- 按创建时间倒序（storage.getMemos() 已排序）',
      '- 顶部 t-input 搜索框，关键词过滤标题+内容',
      '- memo-item 组件渲染，属性：memo 对象',
      '- 点击→编辑弹窗，长按→删除确认',
      '- 空状态："还没有备忘，记点什么吧"',
      '',
      '### memo-item 组件',
      '- 显示：标题+内容预览(截断2行，CSS text-overflow:ellipsis)+创建日期',
      '',
      '## 铁律',
      '- 禁止 WXML 中写 style="..."',
      '- 禁止直接调 wx.Storage 系列 API',
      '- 页面 json 的 usingComponents 注册组件',
    ].join('\n'),
    { label: 'DevB:待办+备忘', phase: '开发' }
  ),

  // ── Dev C: 我的 + 子页面 ──
  () => agent(
    [
      CONTRACT_HEADER,
      '',
      '# 角色：前端开发工程师（我的+子页面模块）',
      '',
      `先读取 ${PROJECT}/pages/mine/mine.js（如果文件不存在或为空，则从零创建 Page({})）。子页面（calendar, detail, write）直接创建。`,
      '',
      '## 你的文件',
      `我的: ${PROJECT}/pages/mine/mine.{js,wxml,wxss,json}`,
      `月历: ${PROJECT}/pages/calendar/calendar.{js,wxml,wxss,json}`,
      `      ${PROJECT}/components/calendar/calendar.{js,wxml,wxss,json}`,
      `详情: ${PROJECT}/pages/detail/detail.{js,wxml,wxss,json}`,
      `写总结: ${PROJECT}/pages/write/write.{js,wxml,wxss,json}`,
      `公共: ${PROJECT}/components/empty-state/empty-state.{js,wxml,wxss,json}`,
      `      ${PROJECT}/components/tag-input/tag-input.{js,wxml,wxss,json}`,
      '',
      '## "我的"页',
      '',
      '### 统计卡片（onShow 中重新计算）',
      '- 🔥 连续 X 天（streak.getStreak()）',
      '- 累计 X 天（storage.getAllEntries().length）',
      '- 共写 X 字（storage.getAllEntries() 累加 content.length）',
      '',
      '### 习惯管理',
      '- 列表展示 storage.getHabitDefs()，每条：图标+名称+编辑/删除按钮',
      '- 添加/编辑：t-popup 弹窗，名称(t-input)+选图标(预设20个emoji)+保存',
      '- 删除：t-dialog 二次确认',
      '- 上限 20 个，超出提示 "习惯太多不易坚持，请先归档不需要的"',
      '',
      '### 存储用量',
      '- 进度条：storage.getStorageUsage() → usedKB/limitKB',
      '- 格式：💾 存储: ██████░░░ X.X/10 MB',
      '- >8MB Toast 警告',
      '',
      '### 设置',
      '- 📤 导出数据 → exp.exportAll() → wx.getFileSystemManager().writeFile() 写入临时文件 → wx.shareFileMessage 分享（不能直接传字符串给 shareFileMessage）',
      '- 📥 导入数据 → wx.chooseMessageFile → exp.importData() → 显示"新增X条，更新Y条"',
      '- 🗑️ 清空数据 → 二次确认+输入"确认清空"，确认后调 storage.clearAll()，红色警告',
      '- ℹ️ 关于 → 弹窗：版本1.0.0/原生+TDesign/本地存储/隐私说明',
      '',
      '### 备份提醒',
      '- onShow 检查：storage.getSetting("last_export_time")，距上次>30天且数据>3MB→顶部轻提示',
      '',
      '## 月历页',
      '',
      '### 日历组件',
      '- ← → 箭头 + swiper 滑动切换月份',
      '- dateUtil.getMonthCalendar(ym) 获取周数组',
      '- 表头：一 二 三 四 五 六 日',
      '- 绿点判定（4 种数据全查，全部走 storage API）：',
      '  1. storage.getAllEntries() → 按 date 建 Set',
      '  2. storage.getAllMoods() → 按 date 建 Set',
      '  3. 对当月每一天调 storage.getHabits(date)，有任意 habit_id 为 true 则该天绿点',
      '  4. storage.getTodos() → JS 层遍历一次按 deadline 分桶到 Map<dateStr, true>，渲染时 O(1) 查',
      '- 今天日期蓝色边框高亮',
      '- 点击某天→navigateTo /pages/detail/detail?date=YYYY-MM-DD',
      '',
      '### 底部统计',
      '- 记录天数：storage.getAllEntries() 中本月 date 数量',
      '- 总字数：本月 entries 累加 content.length',
      '- 习惯完成率：分母=已过天数×习惯数，分子=遍历当月 habit_ 的 true 总数',
      '- 心情分布：storage.getAllMoods() 本月统计',
      '',
      '## 详情页',
      '- onLoad(options) 获取 options.date',
      '- 显示：日期+心情(如有)+日总结+标签+字数+习惯打卡+当日待办',
      '- 底部："续写"→写总结页、"删除"→t-dialog确认',
      '- onShareAppMessage：日期+内容前200字+心情+习惯的纯文本摘要',
      '',
      '## 写总结页',
      '- onLoad(options) 获取 options.date',
      '- 已有内容：storage.getEntry(date) 预填到 t-textarea',
      '- tag-input 组件选标签',
      '- 实时字数统计',
      '- 保存→storage.saveEntry(date, {content, tags})→navigateBack()',
      '',
      '## empty-state 组件',
      '- 属性：icon(emoji), text(提示文字)',
      '- 渲染 .empty-state 居中占位',
      '',
      '## tag-input 组件',
      '- 属性：tags(当前标签数组)',
      '- 预设标签：工作/学习/生活/健康/开发/阅读',
      '- 点击预设标签 toggle，自定义输入用 t-input 的 bind:confirm 事件触发添加',
      '- 触发 onchange 事件，传递更新后的 tags 数组',
      '',
      '## 铁律',
      '- 禁止 WXML 中写 style="..."',
      '- 禁止直接调 wx.Storage 系列 API',
      '- 页面 json 的 usingComponents 注册组件',
    ].join('\n'),
    { label: 'DevC:我的+子页面', phase: '开发' }
  ),
])

const devOk = devResults.filter(Boolean).length
const devNames = ['DevA:首页', 'DevB:待办+备忘', 'DevC:我的+子页面']
const devFailed = devResults.map((r, i) => r ? null : devNames[i]).filter(Boolean)
if (devFailed.length > 0) {
  log(`⚠️ 开发 agent 失败: ${devFailed.join(', ')}。请检查上方错误信息，手动重试或修复后重新执行 workflow。`)
}
log(`开发团队完成：${devOk}/3`)

// ═══════════════════════════════════════════════════════════════
// Phase 3: 审查+测试（3 agent 并行，报告写入文件）
// ═══════════════════════════════════════════════════════════════
phase('审查+测试')

const reviewResults = await parallel([
  // ── UI 设计师 ──
  () => agent(
    [
      `先读取 ${PROJECT}/CONTRACT.md 了解 CSS 变量和 class 规范。`,
      '',
      '# 角色：UI 设计师',
      '',
      '只读文件，不修改代码。',
      '',
      `## 审查范围：${PROJECT} 下所有 .wxml 和 .wxss 文件`,
      '',
      '## 审查清单',
      '1. **inline style**：grep 所有 .wxml 搜索 style="，每个违规列出文件名+行号',
      '2. **CSS 变量**：检查颜色是否用 var(--color-*) 而非硬编码 #333/#666/#999',
      '3. **间距**：是否用 var(--spacing-*) 而非硬编码 px',
      '4. **动画**：心情选择器有 .scale-in？习惯打卡有 .fill-green 过渡？',
      '5. **class 重复**：页面是否重复定义了全局已有的 class（如 .card）',
      '6. **视觉一致性**：卡片间距统一？字体用 var(--font-*)？按钮样式统一？',
      '',
      `## 输出：将报告写入 ${PROJECT}/review-ui.md`,
      '',
      '格式：',
      '```markdown',
      '# UI 审查报告',
      '## 严重（必须修复）',
      '- [ ] 文件:行号 — 问题',
      '## 中等（建议修复）',
      '- [ ] 文件:行号 — 问题',
      '## 轻微（锦上添花）',
      '- [ ] 文件:行号 — 问题',
      '## 评分',
      '- 颜色: X/10 | 间距: X/10 | 动画: X/10 | 组件复用: X/10',
      '```',
    ].join('\n'),
    { label: 'UI设计师', phase: '审查+测试' }
  ),

  // ── QA 测试工程师 ──
  () => agent(
    [
      `先读取 ${PROJECT}/CONTRACT.md 了解 API 签名和路由表。`,
      '',
      '# 角色：QA 测试工程师',
      '',
      '只读文件，不修改代码。',
      '',
      `## 审查范围：${PROJECT} 下所有 .js 和 .json 文件`,
      '',
      '## 测试清单',
      '1. **storage 隔离**：grep wx.setStorageSync / wx.getStorageSync / wx.removeStorageSync，确认只在 utils/storage.js 中',
      '2. **路由正确**：Tab 页面必须用 wx.switchTab，子页面用 wx.navigateTo，路径与 CONTRACT.md 一致',
      '3. **数据流**：onShow 是否刷新？保存后是否更新？删除后是否移除？',
      '4. **边界条件**：空数据有空状态提示？习惯上限 20 有拦截？存储>8MB 有警告？导入>9MB 拒绝？待办无 deadline 首页不显示？习惯删除后 orphan 跳过？',
      '5. **组件注册**：每个页面 .json 的 usingComponents 是否注册了所有组件',
      '6. **需求符合**：连续天数仅统计 entry_？允许写未来日期？日总结续写是覆盖不是追加？',
      '',
      `## 输出：将报告写入 ${PROJECT}/review-qa.md`,
      '',
      '格式：',
      '```markdown',
      '# QA 测试报告',
      '## 致命（阻断功能）',
      '- [ ] 文件:行号 — 问题',
      '## 严重（功能异常）',
      '- [ ] 文件:行号 — 问题',
      '## 一般（边界遗漏）',
      '- [ ] 文件:行号 — 问题',
      '## 建议（体验优化）',
      '- [ ] 场景 — 建议',
      '## 评分',
      '- 存储隔离: X/10 | 路由: X/10 | 数据流: X/10 | 边界: X/10 | 需求符合: X/10',
      '```',
    ].join('\n'),
    { label: 'QA测试', phase: '审查+测试' }
  ),

  // ── 自动化测试 ──
  () => agent(
    [
      '# 角色：自动化测试工程师',
      '',
      '**必须用 Bash 工具逐条执行以下命令，把实际 stdout/stderr 写入报告。禁止只输出命令文本而不执行。**',
      '',
      '每个测试输出 PASS 或 FAIL（带文件名+行号）。',
      '',
      `## 项目路径：${PROJECT}`,
      '',
      '## 测试套件',
      '',
      '### 测试 1：JSON 语法',
      '```bash',
      `python3 << 'PYEOF'`,
      `import json, os`,
      `root = '${PROJECT}'`,
      `errors = []`,
      `for dirpath, _, filenames in os.walk(root):`,
      `    for f in filenames:`,
      `        if f.endswith('.json'):`,
      `            path = os.path.join(dirpath, f)`,
      `            try:`,
      `                with open(path, 'r', encoding='utf-8') as fp:`,
      `                    json.load(fp)`,
      `            except Exception as e:`,
      `                errors.append(f"{path}: {e}")`,
      `if errors:`,
      `    for e in errors:`,
      `        print("FAIL:", e)`,
      `else:`,
      `    print("PASS: 所有 JSON 语法正确")`,
      `PYEOF`,
      '```',
      '',
      '### 测试 2：文件完整性',
      '```bash',
      `python3 -c "`,
      `import os; root='${PROJECT}'; errors=[]`,
      `for area in ['pages','components']:`,
      `  ap=os.path.join(root,area)`,
      `  if not os.path.exists(ap): continue`,
      `  for name in os.listdir(ap):`,
      `    sub=os.path.join(ap,name)`,
      `    if os.path.isdir(sub):`,
      `      for ext in ['.js','.wxml','.wxss','.json']:`,
      `        f=os.path.join(sub,name+ext)`,
      `        if not os.path.exists(f): errors.append(f'MISSING: {f}')`,
      `if errors:`,
      `  for e in errors: print('FAIL',e)`,
      `else: print('PASS: 所有页面和组件文件完整')"`,
      '```',
      '',
      '### 测试 3：页面注册',
      '```bash',
      `python3 -c "`,
      `import json,os; root='${PROJECT}'`,
      `with open(os.path.join(root,'app.json')) as f: config=json.load(f)`,
      `registered=set(config.get('pages',[]))`,
      `actual=set()`,
      `for name in os.listdir(os.path.join(root,'pages')):`,
      `  if os.path.isdir(os.path.join(root,'pages',name)):`,
      `    actual.add(f'pages/{name}/{name}')`,
      `missing=actual-registered; extra=registered-actual`,
      `errors=[]`,
      `if missing:`,
      `  for m in sorted(missing): errors.append(f'未注册: {m}')`,
      `if extra:`,
      `  for e in sorted(extra): errors.append(f'多余: {e}')`,
      `if errors:`,
      `  for e in errors: print('FAIL',e)`,
      `else: print('PASS: 页面注册与目录一致')"`,
      '```',
      '',
      '### 测试 4：组件引用',
      '```bash',
      `python3 -c "`,
      `import json,os; root='${PROJECT}'; errors=[]`,
      `for name in os.listdir(os.path.join(root,'pages')):`,
      `  sub=os.path.join(root,'pages',name)`,
      `  jp=os.path.join(sub,name+'.json')`,
      `  if not os.path.exists(jp): continue`,
      `  with open(jp) as f:`,
      `    try: config=json.load(f)`,
      `    except: continue`,
      `  for cn,cp in config.get('usingComponents',{}).items():`,
      `    if cp.startswith('tdesign-'): continue`,
      `    abs_dir=os.path.dirname(os.path.normpath(os.path.join(sub,cp)))`,
      `    if not os.path.exists(abs_dir):`,
      `      errors.append(f'{name}.json: {cn} → {cp} (目录不存在)')`,
      `if errors:`,
      `  for e in errors: print('FAIL',e)`,
      `else: print('PASS: 组件引用路径有效')"`,
      '```',
      '',
      '### 测试 5：storage 隔离',
      '```bash',
      `cd ${PROJECT} && (grep -rnE "wx\\.(set|get|remove)StorageSync" --include="*.js" . | grep -v "utils/storage.js" | grep -v "utils/streak.js" | grep -v "utils/export.js" | grep -v "node_modules" && echo "FAIL: storage 调用泄漏" || echo "PASS: storage 隔离")`,
      '```',
      '',
      '### 测试 6：inline style',
      '```bash',
      `cd ${PROJECT} && (grep -rn 'style="' --include="*.wxml" . | grep -v "node_modules" && echo "FAIL: 存在 inline style" || echo "PASS: 无 inline style")`,
      '```',
      '',
      '### 测试 7：Tab 路由',
      '```bash',
      `cd ${PROJECT} && (grep -rnE "navigateTo.*['\"]/pages/(todos|memos|mine|index)/" --include="*.js" . | grep -v "node_modules" && echo "FAIL: Tab 页面误用 navigateTo" || echo "PASS: Tab 路由正确")`,
      '```',
      '',
      `## 输出：将报告写入 ${PROJECT}/review-test.md`,
      '',
      '```markdown',
      '# 自动化测试报告',
      '| 测试项 | 结果 | 详情 |',
      '|--------|------|------|',
      '| JSON 语法 | PASS/FAIL | |',
      '| 文件完整性 | PASS/FAIL | |',
      '| 页面注册 | PASS/FAIL | |',
      '| 组件引用 | PASS/FAIL | |',
      '| storage 隔离 | PASS/FAIL | |',
      '| inline style | PASS/FAIL | |',
      '| Tab 路由 | PASS/FAIL | |',
      '总计: X PASS / Y FAIL',
      '门禁: 通过/不通过（全部 PASS 才算通过）',
      '```',
    ].join('\n'),
    { label: '自动化测试', phase: '审查+测试' }
  ),
])

log(`审查+测试完成：${reviewResults.filter(Boolean).length}/3`)

// ═══════════════════════════════════════════════════════════════
// Phase 4: 修复工程师
// 从文件读取 3 份报告，逐个修复。报告在文件里，不撑爆上下文。
// ═══════════════════════════════════════════════════════════════
phase('修复')

const fixer = await agent(
  [
    '# 角色：修复工程师',
    '',
    '## 你的职责',
    '从文件读取审查报告，按优先级修复。修复后重测。',
    '',
    `## 项目路径：${PROJECT}`,
    '',
    '---',
    '',
    '## Step 1：读取审查报告',
    '',
    `先读取 ${PROJECT}/review-test.md（自动化测试报告），优先修复 FAIL 项。`,
    `再读取 ${PROJECT}/review-qa.md（QA 报告），修复致命和严重问题。`,
    `最后读取 ${PROJECT}/review-ui.md（UI 报告），修复严重问题。`,
    '',
    '---',
    '',
    '## Step 2：修复优先级',
    '1. 自动化测试 FAIL（JSON 语法/文件缺失/页面未注册/组件引用无效/storage 泄漏）',
    '2. QA 致命（功能阻断）',
    '3. QA 严重（功能异常）',
    '4. UI 严重（inline style、硬编码颜色）',
    '5. QA 一般（边界遗漏）',
    '6. UI 中等（动画缺失）',
    '',
    '修复一条在报告中勾掉 `- [ ]` 改为 `- [x]`。用 Edit 工具定位到具体的 `- [ ]` 行做精确替换，不要整体重写报告文件。',
    '',
    '---',
    '',
    '## Step 3：修复后重测',
    '全部修复完成后，执行以下 3 个关键测试：',
    '',
    '```bash',
    `# 1. JSON 语法`,
    `python3 << 'PYEOF'`,
    `import json, os`,
    `root = '${PROJECT}'`,
    `ok = True`,
    `for dirpath, _, filenames in os.walk(root):`,
    `    for f in filenames:`,
    `        if f.endswith('.json'):`,
    `            try:`,
    `                with open(os.path.join(dirpath, f)) as fp: json.load(fp)`,
    `            except Exception as e:`,
    `                print(f"FAIL: {os.path.join(dirpath, f)}: {e}")`,
    `                ok = False`,
    `if ok: print("JSON: PASS")`,
    `PYEOF`,
    '',
    `# 2. storage 隔离`,
    `cd ${PROJECT} && (grep -rnE "wx\\.(set|get|remove)StorageSync" --include="*.js" . | grep -v "utils/storage.js" | grep -v "utils/streak.js" | grep -v "utils/export.js" | grep -v "node_modules" && echo "FAIL: storage 调用泄漏" || echo "storage: PASS")`,
    '',
    `# 3. inline style`,
    `cd ${PROJECT} && grep -rn 'style="' --include="*.wxml" . | grep -v "node_modules" || echo "inline: PASS"`,
    '```',
    '',
    '3 项全部 PASS 才算修复完成。',
    '',
    '---',
    '',
    '## Step 4：生成 TabBar 图标',
    '',
    `生成 8 个占位图标到 ${PROJECT}/assets/：`,
    '- today.png / today-active.png',
    '- todo.png / todo-active.png',
    '- memo.png / memo-active.png',
    '- mine.png / mine-active.png',
    '',
    '优先用 Python PIL 生成简单的 81x81 PNG（纯色圆点+简单形状，非激活 #999，激活 #2c3e3e）。',
    '如果环境没有 PIL，用 printf + base64 创建最小占位 PNG 并注明需替换。',
    '',
    '---',
    '',
    '## 输出',
    '1. 已修复的问题清单（勾选）',
    '2. 无法修复的问题及原因',
    '3. 重测结果（3 项 PASS/FAIL）',
    '4. 用户手动操作事项',
  ].join('\n'),
  { label: '修复工程师', phase: '修复' }
)

log('修复完成')

// ═══════════════════════════════════════════════════════════════
// Phase 5: 验收测试
// ═══════════════════════════════════════════════════════════════
phase('验收测试')

const testPlan = await agent(
  [
    '# 角色：测试工程师',
    '',
    '## 你的职责',
    '你不是代码审查员（QA 已经做了），你是验收测试员。',
    '你的工作：把需求文档的每一条功能，对应到实际代码，生成可执行的测试清单。',
    '你只读文件，不修改代码。',
    '',
    `## 项目路径：${PROJECT}`,
    '',
    '---',
    '',
    '## Step 1：读取需求文档',
    `先读取 ${PROJECT}/../REQUIREMENTS.md，了解完整的功能需求。`,
    `再读取 ${PROJECT}/CONTRACT.md，了解路由表、storage API、CSS 变量。`,
    '',
    '---',
    '',
    '## Step 2：需求追溯矩阵',
    '',
    '遍历需求文档的每个功能点，找到对应的实现代码。格式：',
    '',
    '| 需求ID | 需求描述 | 实现文件 | 关键函数/数据 | 状态 |',
    '|--------|---------|---------|-------------|------|',
    '| R1 | 日期切换（箭头+选择器） | pages/index/index.js | onPrevDay/onNextDay/onPickDate | ✅ |',
    '| R2 | 心情选择（5个emoji toggle） | pages/index/index.js | onMoodTap/_loadMood | ✅ |',
    '| ... | ... | ... | ... | ... |',
    '',
    '如果某个需求找不到对应实现，标注"❌ 缺失"。',
    '读取实际代码来确认，不要推测。',
    '',
    '---',
    '',
    '## Step 3：测试用例生成',
    '',
    '对每个功能模块，生成具体的测试步骤。每个用例包含：前置条件、操作步骤、预期结果、⬜ 勾选框。',
    '',
    '```markdown',
    '### TC-01: 日期切换',
    '- 前置: 打开首页',
    '- 步骤:',
    '  1. 点击左箭头 ← → 日期变为前一天',
    '  2. 点击右箭头 → → 日期变为后一天',
    '  3. 点击日期文字 → 弹出原生日期选择器',
    '  4. 选择日期 → 页面切换到所选日期',
    '- 预期: 日期正确切换，选择器正常弹出',
    '- 验证: ⬜ 通过 ⬜ 失败',
    '',
    '### TC-02: 心情选择',
    '- 前置: 打开首页',
    '- 步骤:',
    '  1. 点击😊 → 选中高亮，存入 mood_YYYY-MM-DD',
    '  2. 点击😐 → 切换选中，😊 取消',
    '  3. 再次点击😐 → 取消选中',
    '  4. 切换日期再切回 → 选中状态保持',
    '- 预期: 选中状态正确切换',
    '- 验证: ⬜ 通过 ⬜ 失败',
    '',
    '### TC-03: 习惯打卡',
    '- 前置: 我的页已添加至少 1 个习惯',
    '- 步骤:',
    '  1. 首页点击习惯条目 → 打勾，绿色填充',
    '  2. 再次点击 → 取消打勾',
    '  3. 切换到昨天 → 打勾（补签）',
    '  4. 切回今天 → 昨天状态不影响今天',
    '- 预期: 打卡状态独立，补签正常',
    '- 验证: ⬜ 通过 ⬜ 失败',
    '',
    '### TC-04: 日总结',
    '- 前置: 打开首页',
    '- 步骤:',
    '  1. 输入文字 → 字数实时更新',
    '  2. 点击保存 → Toast "已保存"',
    '  3. 显示内容 + 续写/删除按钮',
    '  4. 点击续写 → 跳转 write 页面',
    '  5. 修改内容 → 保存 → 返回首页',
    '  6. 点击删除 → 确认 → 删除成功',
    '- 预期: CRUD 全流程正常',
    '- 验证: ⬜ 通过 ⬜ 失败',
    '',
    '### TC-05: 待办',
    '- 前置: 已添加待办（在待办页操作）',
    '- 步骤:',
    '  1. 待办页添加待办（标题+截止日期）',
    '  2. 首页待办区显示 deadline ≤ 今天的待办',
    '  3. 无 deadline 的待办不显示在首页',
    '  4. 点击勾选框 → 完成',
    '  5. 点击查看全部 → 跳转待办页',
    '- 预期: 筛选逻辑正确，跨页面数据同步',
    '- 验证: ⬜ 通过 ⬜ 失败',
    '',
    '### TC-06: 备忘',
    '- 前置: 打开备忘页',
    '- 步骤:',
    '  1. 添加备忘（标题+内容）',
    '  2. 列表显示按时间倒序',
    '  3. 搜索关键词 → 过滤结果',
    '  4. 点击条目 → 编辑',
    '  5. 长按条目 → 删除确认',
    '- 预期: CRUD + 搜索正常',
    '- 验证: ⬜ 通过 ⬜ 失败',
    '',
    '### TC-07: 设置',
    '- 前置: 打开我的页',
    '- 步骤:',
    '  1. 查看统计卡片（连续/累计/字数）',
    '  2. 添加/编辑/删除习惯',
    '  3. 导出数据 → 分享',
    '  4. 导入数据 → 合并显示',
    '  5. 清空数据 → 二次确认',
    '  6. 查看关于页',
    '- 预期: 所有设置功能正常',
    '- 验证: ⬜ 通过 ⬜ 失败',
    '',
    '### TC-08: 月历',
    '- 前置: 打开我的页 → 月历',
    '- 步骤:',
    '  1. ← → 切换月份',
    '  2. 有记录的日期显示绿点',
    '  3. 点击某天 → 跳转详情页',
    '  4. 底部统计正确',
    '- 预期: 月历渲染正确',
    '- 验证: ⬜ 通过 ⬜ 失败',
    '```',
    '',
    '---',
    '',
    '## Step 4：边界条件测试',
    '',
    '检查以下边界场景，确认代码有对应处理：',
    '',
    '| 场景 | 预期行为 | 代码位置 | 状态 |',
    '|------|---------|---------|------|',
    '| 首次使用（无任何数据） | 所有空状态正确显示 | 各页面 wx:if | ⬜ |',
    '| 切换日期到无数据的一天 | 正常显示空状态 | _loadEntry/_loadMood | ⬜ |',
    '| 快速连续点击 | 无崩溃 | - | ⬜ |',
    '| 输入超长文本 | 无溢出 | textarea maxlength | ⬜ |',
    '| 存储接近 10MB | 警告提示 | storage.checkStorageLimit | ⬜ |',
    '| 导入超大 JSON | 拒绝并提示 | export.importData | ⬜ |',
    '| 习惯定义上限 20 | 拦截并提示 | mine.js | ⬜ |',
    '| 备忘超过 5000 字 | 提示建议拆分 | memos.js | ⬜ |',
    '',
    '---',
    '',
    '## Step 5：跨页面流程测试',
    '',
    '| 流程 | 步骤 | 验证 |',
    '|------|------|------|',
    '| 写日记闭环 | 首页→写总结→保存→返回首页→内容更新 | ⬜ |',
    '| 待办闭环 | 首页→查看全部→待办页→筛选→编辑→返回首页 | ⬜ |',
    '| 习惯闭环 | 我的→添加习惯→返回首页→新习惯出现在打卡列表 | ⬜ |',
    '| 数据闭环 | 我的→导出→清空→导入→数据恢复 | ⬜ |',
    '| 月历闭环 | 首页→我的→月历→点击某天→详情→续写→保存 | ⬜ |',
    '',
    `## 输出：将测试计划写入 ${PROJECT}/test-plan.md`,
    '',
    '格式为 Markdown，包含需求追溯矩阵 + 测试用例 + 边界条件 + 跨页面流程，每项带 ⬜ 勾选框便于手动验证。',
    '',
    '最后输出：测试用例总数、已覆盖需求数、未覆盖需求数、建议补充的测试。',
  ].join('\n'),
  { label: '测试工程师', phase: '验收测试' }
)

log(`验收测试：${testPlan ? 'test-plan.md 已生成' : '跳过'}`)

// ═══════════════════════════════════════════════════════════════
return {
  team: {
    architect: `${architectResults.filter(Boolean).length}/2 succeeded`,
    dev: `${devOk}/3 succeeded`,
    review: `${reviewResults.filter(Boolean).length}/3 succeeded`,
    fixer: fixer ? 'done' : 'failed',
    tester: testPlan ? 'test-plan.md delivered' : 'skipped',
  },
  project: PROJECT,
  reports: [
    `${PROJECT}/review-ui.md`,
    `${PROJECT}/review-qa.md`,
    `${PROJECT}/review-test.md`,
    `${PROJECT}/test-plan.md`,
  ],
  manual: [
    '1. 微信开发者工具打开项目',
    '2. npm install tdesign-miniprogram → 工具→构建 npm',
    '3. 替换 assets/ 图标（如生成了占位图）',
    '4. 点击"预览"生成二维码，手机扫码测试',
  ],
}